package Problem2;

/*
Problem 2
Mon Jan 23 2012

Each new term in the Fibonacci sequence 
is generated by adding the previous two terms.
 By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values
do not exceed four million,
find the sum of the even-valued terms.
   */
public class Problem2
{
    public static int ex = 10;//133 for first 10
    public static int limit = 4000000;
    public static int a = 0;
    public static int b = 1;
    public static int c = 1;
    public static int sum = 0;
    public static void main()
    {
      while(c < limit)
      {  
            if(c % 2 ==0)
            {
                sum+=c;
            }
            a = b;
            b = c;
            c = a + b;
            SOP("\n"+c);
      }
      SOP("\nThe sum of all the even terms in the fib seq < 4mil ");
      SOP("\n"+sum);
    }
    public static void SOP(String s)
    {
        System.out.print(s);
    }
    
}
